[programs.ls] # Maybe we can remove the "programs."
cmd = "/bin/ls"
args = ["-la"]
numprocs = 1
umask = 22
workingdir = "." # Set it in the env?
autostart = true
autorestart = "unexpected"
exitcodes = [0, 2]
startretries = 3
starttime = 5
stopsignal = "TERM"
stoptime = 10
stdout = "/tmp/ls.stdout"
stderr = "/tmp/ls.stderr"

[programs.ls.env]

[programs.echo] # Maybe we can remove the "programs."
cmd = "/usr/bin/echo"
args = ["-n", "This is an ECHO test"]
numprocs = 1
umask = 22
workingdir = "/tmp" # Set it in the env?
autostart = true
autorestart = "unexpected"
exitcodes = [0, 2]
startretries = 3
starttime = 5
stopsignal = "TERM"
stoptime = 10
stdout = "/tmp/echo.stdout"
stderr = "/tmp/echo.stderr"

[programs.echo.env]

[programs.false]
cmd = "/usr/bin/false"
args = ["--version"]
numprocs = 1
umask = 22
workingdir = "." # Set it in the env?
autostart = true
autorestart = "unexpected"
exitcodes = [0, 2]
startretries = 3
starttime = 5
stopsignal = "TERM"
stoptime = 10
stdout = "/tmp/false.stdout"
stderr = "/tmp/false.stderr"

[programs.false.env]