[programs.ls] # Maybe we can remove the "programs."
cmd = "/bin/ls"
numprocs = 1
umask = 22
workingdir = "/tmp" # Set it in the env?
autostart = true
autorestart = "unexpected"
exitcodes = [0, 2]
startretries = 3
starttime = 5
stopsignal = "TERM"
stoptime = 10
stdout = "/tmp/ls.stdout"
stderr = "/tmp/ls.stderr"

[programs.ls.env]
